# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:\MyProjects\GUIs\QT_QML_Course_KDAB\QT_QML_Course_KDAB

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:\MyProjects\GUIs\QT_QML_Course_KDAB\QT_QML_Course_KDAB

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	"C:\Program Files\CMake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	"C:\Program Files\CMake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:\MyProjects\GUIs\QT_QML_Course_KDAB\QT_QML_Course_KDAB\CMakeFiles D:\MyProjects\GUIs\QT_QML_Course_KDAB\QT_QML_Course_KDAB\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start D:\MyProjects\GUIs\QT_QML_Course_KDAB\QT_QML_Course_KDAB\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named appQML_1

# Build rule for target.
appQML_1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 appQML_1
.PHONY : appQML_1

# fast build rule for target.
appQML_1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appQML_1.dir\build.make CMakeFiles/appQML_1.dir/build
.PHONY : appQML_1/fast

#=============================================================================
# Target rules for targets named appQML_1_qmltyperegistration

# Build rule for target.
appQML_1_qmltyperegistration: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 appQML_1_qmltyperegistration
.PHONY : appQML_1_qmltyperegistration

# fast build rule for target.
appQML_1_qmltyperegistration/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appQML_1_qmltyperegistration.dir\build.make CMakeFiles/appQML_1_qmltyperegistration.dir/build
.PHONY : appQML_1_qmltyperegistration/fast

#=============================================================================
# Target rules for targets named all_qmltyperegistrations

# Build rule for target.
all_qmltyperegistrations: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all_qmltyperegistrations
.PHONY : all_qmltyperegistrations

# fast build rule for target.
all_qmltyperegistrations/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\all_qmltyperegistrations.dir\build.make CMakeFiles/all_qmltyperegistrations.dir/build
.PHONY : all_qmltyperegistrations/fast

#=============================================================================
# Target rules for targets named appQML_1_qmllint

# Build rule for target.
appQML_1_qmllint: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 appQML_1_qmllint
.PHONY : appQML_1_qmllint

# fast build rule for target.
appQML_1_qmllint/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appQML_1_qmllint.dir\build.make CMakeFiles/appQML_1_qmllint.dir/build
.PHONY : appQML_1_qmllint/fast

#=============================================================================
# Target rules for targets named appQML_1_qmllint_json

# Build rule for target.
appQML_1_qmllint_json: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 appQML_1_qmllint_json
.PHONY : appQML_1_qmllint_json

# fast build rule for target.
appQML_1_qmllint_json/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appQML_1_qmllint_json.dir\build.make CMakeFiles/appQML_1_qmllint_json.dir/build
.PHONY : appQML_1_qmllint_json/fast

#=============================================================================
# Target rules for targets named appQML_1_qmllint_module

# Build rule for target.
appQML_1_qmllint_module: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 appQML_1_qmllint_module
.PHONY : appQML_1_qmllint_module

# fast build rule for target.
appQML_1_qmllint_module/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appQML_1_qmllint_module.dir\build.make CMakeFiles/appQML_1_qmllint_module.dir/build
.PHONY : appQML_1_qmllint_module/fast

#=============================================================================
# Target rules for targets named all_qmllint

# Build rule for target.
all_qmllint: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all_qmllint
.PHONY : all_qmllint

# fast build rule for target.
all_qmllint/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\all_qmllint.dir\build.make CMakeFiles/all_qmllint.dir/build
.PHONY : all_qmllint/fast

#=============================================================================
# Target rules for targets named all_qmllint_json

# Build rule for target.
all_qmllint_json: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all_qmllint_json
.PHONY : all_qmllint_json

# fast build rule for target.
all_qmllint_json/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\all_qmllint_json.dir\build.make CMakeFiles/all_qmllint_json.dir/build
.PHONY : all_qmllint_json/fast

#=============================================================================
# Target rules for targets named all_qmllint_module

# Build rule for target.
all_qmllint_module: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all_qmllint_module
.PHONY : all_qmllint_module

# fast build rule for target.
all_qmllint_module/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\all_qmllint_module.dir\build.make CMakeFiles/all_qmllint_module.dir/build
.PHONY : all_qmllint_module/fast

#=============================================================================
# Target rules for targets named appQML_1_copy_qml

# Build rule for target.
appQML_1_copy_qml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 appQML_1_copy_qml
.PHONY : appQML_1_copy_qml

# fast build rule for target.
appQML_1_copy_qml/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appQML_1_copy_qml.dir\build.make CMakeFiles/appQML_1_copy_qml.dir/build
.PHONY : appQML_1_copy_qml/fast

#=============================================================================
# Target rules for targets named appQML_1_copy_res

# Build rule for target.
appQML_1_copy_res: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 appQML_1_copy_res
.PHONY : appQML_1_copy_res

# fast build rule for target.
appQML_1_copy_res/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appQML_1_copy_res.dir\build.make CMakeFiles/appQML_1_copy_res.dir/build
.PHONY : appQML_1_copy_res/fast

#=============================================================================
# Target rules for targets named module_appQML_1_aotstats_target

# Build rule for target.
module_appQML_1_aotstats_target: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 module_appQML_1_aotstats_target
.PHONY : module_appQML_1_aotstats_target

# fast build rule for target.
module_appQML_1_aotstats_target/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\module_appQML_1_aotstats_target.dir\build.make CMakeFiles/module_appQML_1_aotstats_target.dir/build
.PHONY : module_appQML_1_aotstats_target/fast

#=============================================================================
# Target rules for targets named all_aotstats

# Build rule for target.
all_aotstats: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all_aotstats
.PHONY : all_aotstats

# fast build rule for target.
all_aotstats/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\all_aotstats.dir\build.make CMakeFiles/all_aotstats.dir/build
.PHONY : all_aotstats/fast

#=============================================================================
# Target rules for targets named appQML_1_qmlimportscan

# Build rule for target.
appQML_1_qmlimportscan: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 appQML_1_qmlimportscan
.PHONY : appQML_1_qmlimportscan

# fast build rule for target.
appQML_1_qmlimportscan/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appQML_1_qmlimportscan.dir\build.make CMakeFiles/appQML_1_qmlimportscan.dir/build
.PHONY : appQML_1_qmlimportscan/fast

#=============================================================================
# Target rules for targets named appQML_1_autogen_timestamp_deps

# Build rule for target.
appQML_1_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 appQML_1_autogen_timestamp_deps
.PHONY : appQML_1_autogen_timestamp_deps

# fast build rule for target.
appQML_1_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appQML_1_autogen_timestamp_deps.dir\build.make CMakeFiles/appQML_1_autogen_timestamp_deps.dir/build
.PHONY : appQML_1_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named appQML_1_autogen

# Build rule for target.
appQML_1_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 appQML_1_autogen
.PHONY : appQML_1_autogen

# fast build rule for target.
appQML_1_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appQML_1_autogen.dir\build.make CMakeFiles/appQML_1_autogen.dir/build
.PHONY : appQML_1_autogen/fast

.qt/rcc/qrc_appQML_1_raw_qml_0.obj: .qt/rcc/qrc_appQML_1_raw_qml_0.cpp.obj
.PHONY : .qt/rcc/qrc_appQML_1_raw_qml_0.obj

# target to build an object file
.qt/rcc/qrc_appQML_1_raw_qml_0.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appQML_1.dir\build.make CMakeFiles/appQML_1.dir/.qt/rcc/qrc_appQML_1_raw_qml_0.cpp.obj
.PHONY : .qt/rcc/qrc_appQML_1_raw_qml_0.cpp.obj

.qt/rcc/qrc_appQML_1_raw_qml_0.i: .qt/rcc/qrc_appQML_1_raw_qml_0.cpp.i
.PHONY : .qt/rcc/qrc_appQML_1_raw_qml_0.i

# target to preprocess a source file
.qt/rcc/qrc_appQML_1_raw_qml_0.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appQML_1.dir\build.make CMakeFiles/appQML_1.dir/.qt/rcc/qrc_appQML_1_raw_qml_0.cpp.i
.PHONY : .qt/rcc/qrc_appQML_1_raw_qml_0.cpp.i

.qt/rcc/qrc_appQML_1_raw_qml_0.s: .qt/rcc/qrc_appQML_1_raw_qml_0.cpp.s
.PHONY : .qt/rcc/qrc_appQML_1_raw_qml_0.s

# target to generate assembly for a file
.qt/rcc/qrc_appQML_1_raw_qml_0.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appQML_1.dir\build.make CMakeFiles/appQML_1.dir/.qt/rcc/qrc_appQML_1_raw_qml_0.cpp.s
.PHONY : .qt/rcc/qrc_appQML_1_raw_qml_0.cpp.s

.qt/rcc/qrc_qmake_QML_1.obj: .qt/rcc/qrc_qmake_QML_1.cpp.obj
.PHONY : .qt/rcc/qrc_qmake_QML_1.obj

# target to build an object file
.qt/rcc/qrc_qmake_QML_1.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appQML_1.dir\build.make CMakeFiles/appQML_1.dir/.qt/rcc/qrc_qmake_QML_1.cpp.obj
.PHONY : .qt/rcc/qrc_qmake_QML_1.cpp.obj

.qt/rcc/qrc_qmake_QML_1.i: .qt/rcc/qrc_qmake_QML_1.cpp.i
.PHONY : .qt/rcc/qrc_qmake_QML_1.i

# target to preprocess a source file
.qt/rcc/qrc_qmake_QML_1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appQML_1.dir\build.make CMakeFiles/appQML_1.dir/.qt/rcc/qrc_qmake_QML_1.cpp.i
.PHONY : .qt/rcc/qrc_qmake_QML_1.cpp.i

.qt/rcc/qrc_qmake_QML_1.s: .qt/rcc/qrc_qmake_QML_1.cpp.s
.PHONY : .qt/rcc/qrc_qmake_QML_1.s

# target to generate assembly for a file
.qt/rcc/qrc_qmake_QML_1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appQML_1.dir\build.make CMakeFiles/appQML_1.dir/.qt/rcc/qrc_qmake_QML_1.cpp.s
.PHONY : .qt/rcc/qrc_qmake_QML_1.cpp.s

.rcc/qmlcache/appQML_1_Button_qml.obj: .rcc/qmlcache/appQML_1_Button_qml.cpp.obj
.PHONY : .rcc/qmlcache/appQML_1_Button_qml.obj

# target to build an object file
.rcc/qmlcache/appQML_1_Button_qml.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appQML_1.dir\build.make CMakeFiles/appQML_1.dir/.rcc/qmlcache/appQML_1_Button_qml.cpp.obj
.PHONY : .rcc/qmlcache/appQML_1_Button_qml.cpp.obj

.rcc/qmlcache/appQML_1_Button_qml.i: .rcc/qmlcache/appQML_1_Button_qml.cpp.i
.PHONY : .rcc/qmlcache/appQML_1_Button_qml.i

# target to preprocess a source file
.rcc/qmlcache/appQML_1_Button_qml.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appQML_1.dir\build.make CMakeFiles/appQML_1.dir/.rcc/qmlcache/appQML_1_Button_qml.cpp.i
.PHONY : .rcc/qmlcache/appQML_1_Button_qml.cpp.i

.rcc/qmlcache/appQML_1_Button_qml.s: .rcc/qmlcache/appQML_1_Button_qml.cpp.s
.PHONY : .rcc/qmlcache/appQML_1_Button_qml.s

# target to generate assembly for a file
.rcc/qmlcache/appQML_1_Button_qml.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appQML_1.dir\build.make CMakeFiles/appQML_1.dir/.rcc/qmlcache/appQML_1_Button_qml.cpp.s
.PHONY : .rcc/qmlcache/appQML_1_Button_qml.cpp.s

.rcc/qmlcache/appQML_1_CheckBox_qml.obj: .rcc/qmlcache/appQML_1_CheckBox_qml.cpp.obj
.PHONY : .rcc/qmlcache/appQML_1_CheckBox_qml.obj

# target to build an object file
.rcc/qmlcache/appQML_1_CheckBox_qml.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appQML_1.dir\build.make CMakeFiles/appQML_1.dir/.rcc/qmlcache/appQML_1_CheckBox_qml.cpp.obj
.PHONY : .rcc/qmlcache/appQML_1_CheckBox_qml.cpp.obj

.rcc/qmlcache/appQML_1_CheckBox_qml.i: .rcc/qmlcache/appQML_1_CheckBox_qml.cpp.i
.PHONY : .rcc/qmlcache/appQML_1_CheckBox_qml.i

# target to preprocess a source file
.rcc/qmlcache/appQML_1_CheckBox_qml.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appQML_1.dir\build.make CMakeFiles/appQML_1.dir/.rcc/qmlcache/appQML_1_CheckBox_qml.cpp.i
.PHONY : .rcc/qmlcache/appQML_1_CheckBox_qml.cpp.i

.rcc/qmlcache/appQML_1_CheckBox_qml.s: .rcc/qmlcache/appQML_1_CheckBox_qml.cpp.s
.PHONY : .rcc/qmlcache/appQML_1_CheckBox_qml.s

# target to generate assembly for a file
.rcc/qmlcache/appQML_1_CheckBox_qml.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appQML_1.dir\build.make CMakeFiles/appQML_1.dir/.rcc/qmlcache/appQML_1_CheckBox_qml.cpp.s
.PHONY : .rcc/qmlcache/appQML_1_CheckBox_qml.cpp.s

.rcc/qmlcache/appQML_1_InputField_qml.obj: .rcc/qmlcache/appQML_1_InputField_qml.cpp.obj
.PHONY : .rcc/qmlcache/appQML_1_InputField_qml.obj

# target to build an object file
.rcc/qmlcache/appQML_1_InputField_qml.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appQML_1.dir\build.make CMakeFiles/appQML_1.dir/.rcc/qmlcache/appQML_1_InputField_qml.cpp.obj
.PHONY : .rcc/qmlcache/appQML_1_InputField_qml.cpp.obj

.rcc/qmlcache/appQML_1_InputField_qml.i: .rcc/qmlcache/appQML_1_InputField_qml.cpp.i
.PHONY : .rcc/qmlcache/appQML_1_InputField_qml.i

# target to preprocess a source file
.rcc/qmlcache/appQML_1_InputField_qml.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appQML_1.dir\build.make CMakeFiles/appQML_1.dir/.rcc/qmlcache/appQML_1_InputField_qml.cpp.i
.PHONY : .rcc/qmlcache/appQML_1_InputField_qml.cpp.i

.rcc/qmlcache/appQML_1_InputField_qml.s: .rcc/qmlcache/appQML_1_InputField_qml.cpp.s
.PHONY : .rcc/qmlcache/appQML_1_InputField_qml.s

# target to generate assembly for a file
.rcc/qmlcache/appQML_1_InputField_qml.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appQML_1.dir\build.make CMakeFiles/appQML_1.dir/.rcc/qmlcache/appQML_1_InputField_qml.cpp.s
.PHONY : .rcc/qmlcache/appQML_1_InputField_qml.cpp.s

.rcc/qmlcache/appQML_1_LineEdit_qml.obj: .rcc/qmlcache/appQML_1_LineEdit_qml.cpp.obj
.PHONY : .rcc/qmlcache/appQML_1_LineEdit_qml.obj

# target to build an object file
.rcc/qmlcache/appQML_1_LineEdit_qml.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appQML_1.dir\build.make CMakeFiles/appQML_1.dir/.rcc/qmlcache/appQML_1_LineEdit_qml.cpp.obj
.PHONY : .rcc/qmlcache/appQML_1_LineEdit_qml.cpp.obj

.rcc/qmlcache/appQML_1_LineEdit_qml.i: .rcc/qmlcache/appQML_1_LineEdit_qml.cpp.i
.PHONY : .rcc/qmlcache/appQML_1_LineEdit_qml.i

# target to preprocess a source file
.rcc/qmlcache/appQML_1_LineEdit_qml.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appQML_1.dir\build.make CMakeFiles/appQML_1.dir/.rcc/qmlcache/appQML_1_LineEdit_qml.cpp.i
.PHONY : .rcc/qmlcache/appQML_1_LineEdit_qml.cpp.i

.rcc/qmlcache/appQML_1_LineEdit_qml.s: .rcc/qmlcache/appQML_1_LineEdit_qml.cpp.s
.PHONY : .rcc/qmlcache/appQML_1_LineEdit_qml.s

# target to generate assembly for a file
.rcc/qmlcache/appQML_1_LineEdit_qml.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appQML_1.dir\build.make CMakeFiles/appQML_1.dir/.rcc/qmlcache/appQML_1_LineEdit_qml.cpp.s
.PHONY : .rcc/qmlcache/appQML_1_LineEdit_qml.cpp.s

.rcc/qmlcache/appQML_1_Main_qml.obj: .rcc/qmlcache/appQML_1_Main_qml.cpp.obj
.PHONY : .rcc/qmlcache/appQML_1_Main_qml.obj

# target to build an object file
.rcc/qmlcache/appQML_1_Main_qml.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appQML_1.dir\build.make CMakeFiles/appQML_1.dir/.rcc/qmlcache/appQML_1_Main_qml.cpp.obj
.PHONY : .rcc/qmlcache/appQML_1_Main_qml.cpp.obj

.rcc/qmlcache/appQML_1_Main_qml.i: .rcc/qmlcache/appQML_1_Main_qml.cpp.i
.PHONY : .rcc/qmlcache/appQML_1_Main_qml.i

# target to preprocess a source file
.rcc/qmlcache/appQML_1_Main_qml.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appQML_1.dir\build.make CMakeFiles/appQML_1.dir/.rcc/qmlcache/appQML_1_Main_qml.cpp.i
.PHONY : .rcc/qmlcache/appQML_1_Main_qml.cpp.i

.rcc/qmlcache/appQML_1_Main_qml.s: .rcc/qmlcache/appQML_1_Main_qml.cpp.s
.PHONY : .rcc/qmlcache/appQML_1_Main_qml.s

# target to generate assembly for a file
.rcc/qmlcache/appQML_1_Main_qml.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appQML_1.dir\build.make CMakeFiles/appQML_1.dir/.rcc/qmlcache/appQML_1_Main_qml.cpp.s
.PHONY : .rcc/qmlcache/appQML_1_Main_qml.cpp.s

.rcc/qmlcache/appQML_1_qmlcache_loader.obj: .rcc/qmlcache/appQML_1_qmlcache_loader.cpp.obj
.PHONY : .rcc/qmlcache/appQML_1_qmlcache_loader.obj

# target to build an object file
.rcc/qmlcache/appQML_1_qmlcache_loader.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appQML_1.dir\build.make CMakeFiles/appQML_1.dir/.rcc/qmlcache/appQML_1_qmlcache_loader.cpp.obj
.PHONY : .rcc/qmlcache/appQML_1_qmlcache_loader.cpp.obj

.rcc/qmlcache/appQML_1_qmlcache_loader.i: .rcc/qmlcache/appQML_1_qmlcache_loader.cpp.i
.PHONY : .rcc/qmlcache/appQML_1_qmlcache_loader.i

# target to preprocess a source file
.rcc/qmlcache/appQML_1_qmlcache_loader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appQML_1.dir\build.make CMakeFiles/appQML_1.dir/.rcc/qmlcache/appQML_1_qmlcache_loader.cpp.i
.PHONY : .rcc/qmlcache/appQML_1_qmlcache_loader.cpp.i

.rcc/qmlcache/appQML_1_qmlcache_loader.s: .rcc/qmlcache/appQML_1_qmlcache_loader.cpp.s
.PHONY : .rcc/qmlcache/appQML_1_qmlcache_loader.s

# target to generate assembly for a file
.rcc/qmlcache/appQML_1_qmlcache_loader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appQML_1.dir\build.make CMakeFiles/appQML_1.dir/.rcc/qmlcache/appQML_1_qmlcache_loader.cpp.s
.PHONY : .rcc/qmlcache/appQML_1_qmlcache_loader.cpp.s

appQML_1_autogen/mocs_compilation.obj: appQML_1_autogen/mocs_compilation.cpp.obj
.PHONY : appQML_1_autogen/mocs_compilation.obj

# target to build an object file
appQML_1_autogen/mocs_compilation.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appQML_1.dir\build.make CMakeFiles/appQML_1.dir/appQML_1_autogen/mocs_compilation.cpp.obj
.PHONY : appQML_1_autogen/mocs_compilation.cpp.obj

appQML_1_autogen/mocs_compilation.i: appQML_1_autogen/mocs_compilation.cpp.i
.PHONY : appQML_1_autogen/mocs_compilation.i

# target to preprocess a source file
appQML_1_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appQML_1.dir\build.make CMakeFiles/appQML_1.dir/appQML_1_autogen/mocs_compilation.cpp.i
.PHONY : appQML_1_autogen/mocs_compilation.cpp.i

appQML_1_autogen/mocs_compilation.s: appQML_1_autogen/mocs_compilation.cpp.s
.PHONY : appQML_1_autogen/mocs_compilation.s

# target to generate assembly for a file
appQML_1_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appQML_1.dir\build.make CMakeFiles/appQML_1.dir/appQML_1_autogen/mocs_compilation.cpp.s
.PHONY : appQML_1_autogen/mocs_compilation.cpp.s

appqml_1_qmltyperegistrations.obj: appqml_1_qmltyperegistrations.cpp.obj
.PHONY : appqml_1_qmltyperegistrations.obj

# target to build an object file
appqml_1_qmltyperegistrations.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appQML_1.dir\build.make CMakeFiles/appQML_1.dir/appqml_1_qmltyperegistrations.cpp.obj
.PHONY : appqml_1_qmltyperegistrations.cpp.obj

appqml_1_qmltyperegistrations.i: appqml_1_qmltyperegistrations.cpp.i
.PHONY : appqml_1_qmltyperegistrations.i

# target to preprocess a source file
appqml_1_qmltyperegistrations.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appQML_1.dir\build.make CMakeFiles/appQML_1.dir/appqml_1_qmltyperegistrations.cpp.i
.PHONY : appqml_1_qmltyperegistrations.cpp.i

appqml_1_qmltyperegistrations.s: appqml_1_qmltyperegistrations.cpp.s
.PHONY : appqml_1_qmltyperegistrations.s

# target to generate assembly for a file
appqml_1_qmltyperegistrations.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appQML_1.dir\build.make CMakeFiles/appQML_1.dir/appqml_1_qmltyperegistrations.cpp.s
.PHONY : appqml_1_qmltyperegistrations.cpp.s

main.obj: main.cpp.obj
.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appQML_1.dir\build.make CMakeFiles/appQML_1.dir/main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appQML_1.dir\build.make CMakeFiles/appQML_1.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appQML_1.dir\build.make CMakeFiles/appQML_1.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... install
	@echo ... install/local
	@echo ... install/strip
	@echo ... list_install_components
	@echo ... rebuild_cache
	@echo ... all_aotstats
	@echo ... all_qmllint
	@echo ... all_qmllint_json
	@echo ... all_qmllint_module
	@echo ... all_qmltyperegistrations
	@echo ... appQML_1_autogen
	@echo ... appQML_1_autogen_timestamp_deps
	@echo ... appQML_1_copy_qml
	@echo ... appQML_1_copy_res
	@echo ... appQML_1_qmlimportscan
	@echo ... appQML_1_qmllint
	@echo ... appQML_1_qmllint_json
	@echo ... appQML_1_qmllint_module
	@echo ... appQML_1_qmltyperegistration
	@echo ... module_appQML_1_aotstats_target
	@echo ... appQML_1
	@echo ... .qt/rcc/qrc_appQML_1_raw_qml_0.obj
	@echo ... .qt/rcc/qrc_appQML_1_raw_qml_0.i
	@echo ... .qt/rcc/qrc_appQML_1_raw_qml_0.s
	@echo ... .qt/rcc/qrc_qmake_QML_1.obj
	@echo ... .qt/rcc/qrc_qmake_QML_1.i
	@echo ... .qt/rcc/qrc_qmake_QML_1.s
	@echo ... .rcc/qmlcache/appQML_1_Button_qml.obj
	@echo ... .rcc/qmlcache/appQML_1_Button_qml.i
	@echo ... .rcc/qmlcache/appQML_1_Button_qml.s
	@echo ... .rcc/qmlcache/appQML_1_CheckBox_qml.obj
	@echo ... .rcc/qmlcache/appQML_1_CheckBox_qml.i
	@echo ... .rcc/qmlcache/appQML_1_CheckBox_qml.s
	@echo ... .rcc/qmlcache/appQML_1_InputField_qml.obj
	@echo ... .rcc/qmlcache/appQML_1_InputField_qml.i
	@echo ... .rcc/qmlcache/appQML_1_InputField_qml.s
	@echo ... .rcc/qmlcache/appQML_1_LineEdit_qml.obj
	@echo ... .rcc/qmlcache/appQML_1_LineEdit_qml.i
	@echo ... .rcc/qmlcache/appQML_1_LineEdit_qml.s
	@echo ... .rcc/qmlcache/appQML_1_Main_qml.obj
	@echo ... .rcc/qmlcache/appQML_1_Main_qml.i
	@echo ... .rcc/qmlcache/appQML_1_Main_qml.s
	@echo ... .rcc/qmlcache/appQML_1_qmlcache_loader.obj
	@echo ... .rcc/qmlcache/appQML_1_qmlcache_loader.i
	@echo ... .rcc/qmlcache/appQML_1_qmlcache_loader.s
	@echo ... appQML_1_autogen/mocs_compilation.obj
	@echo ... appQML_1_autogen/mocs_compilation.i
	@echo ... appQML_1_autogen/mocs_compilation.s
	@echo ... appqml_1_qmltyperegistrations.obj
	@echo ... appqml_1_qmltyperegistrations.i
	@echo ... appqml_1_qmltyperegistrations.s
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

