
set(target "appQML_1")
set(working_dir "D:/MyProjects/GUIs/QT_QML_Course_KDAB/QT_QML_Course_KDAB")
set(src_and_dest_list
    "D:/MyProjects/GUIs/QT_QML_Course_KDAB/QT_QML_Course_KDAB/Images/ssyss.png"
    "D:/MyProjects/GUIs/QT_QML_Course_KDAB/QT_QML_Course_KDAB/QML_1/Images/ssyss.png"
    "D:/MyProjects/GUIs/QT_QML_Course_KDAB/QT_QML_Course_KDAB/Images/wp2757832.gif"
    "D:/MyProjects/GUIs/QT_QML_Course_KDAB/QT_QML_Course_KDAB/QML_1/Images/wp2757832.gif"
    "D:/MyProjects/GUIs/QT_QML_Course_KDAB/QT_QML_Course_KDAB/Images/Spider-Man-Becomes-Black-Spider-Man-Vemon.jpg"
    "D:/MyProjects/GUIs/QT_QML_Course_KDAB/QT_QML_Course_KDAB/QML_1/Images/Spider-Man-Becomes-Black-Spider-Man-Vemon.jpg"
    "D:/MyProjects/GUIs/QT_QML_Course_KDAB/QT_QML_Course_KDAB/Images/unlocked.png"
    "D:/MyProjects/GUIs/QT_QML_Course_KDAB/QT_QML_Course_KDAB/QML_1/Images/unlocked.png"
    "D:/MyProjects/GUIs/QT_QML_Course_KDAB/QT_QML_Course_KDAB/Images/clock.png"
    "D:/MyProjects/GUIs/QT_QML_Course_KDAB/QT_QML_Course_KDAB/QML_1/Images/clock.png"
    "D:/MyProjects/GUIs/QT_QML_Course_KDAB/QT_QML_Course_KDAB/Images/hour.png"
    "D:/MyProjects/GUIs/QT_QML_Course_KDAB/QT_QML_Course_KDAB/QML_1/Images/hour.png"
    "D:/MyProjects/GUIs/QT_QML_Course_KDAB/QT_QML_Course_KDAB/Images/min.png"
    "D:/MyProjects/GUIs/QT_QML_Course_KDAB/QT_QML_Course_KDAB/QML_1/Images/min.png"
    "D:/MyProjects/GUIs/QT_QML_Course_KDAB/QT_QML_Course_KDAB/Images/rocket.png"
    "D:/MyProjects/GUIs/QT_QML_Course_KDAB/QT_QML_Course_KDAB/QML_1/Images/rocket.png"
    "D:/MyProjects/GUIs/QT_QML_Course_KDAB/QT_QML_Course_KDAB/Images/checked.svg"
    "D:/MyProjects/GUIs/QT_QML_Course_KDAB/QT_QML_Course_KDAB/QML_1/Images/checked.svg"
    "D:/MyProjects/GUIs/QT_QML_Course_KDAB/QT_QML_Course_KDAB/Images/unchecked.svg"
    "D:/MyProjects/GUIs/QT_QML_Course_KDAB/QT_QML_Course_KDAB/QML_1/Images/unchecked.svg"
    "D:/MyProjects/GUIs/QT_QML_Course_KDAB/QT_QML_Course_KDAB/Images/button.png"
    "D:/MyProjects/GUIs/QT_QML_Course_KDAB/QT_QML_Course_KDAB/QML_1/Images/button.png"
    "D:/MyProjects/GUIs/QT_QML_Course_KDAB/QT_QML_Course_KDAB/Images/image0.jpg"
    "D:/MyProjects/GUIs/QT_QML_Course_KDAB/QT_QML_Course_KDAB/QML_1/Images/image0.jpg"
    "D:/MyProjects/GUIs/QT_QML_Course_KDAB/QT_QML_Course_KDAB/Images/image1.jpg"
    "D:/MyProjects/GUIs/QT_QML_Course_KDAB/QT_QML_Course_KDAB/QML_1/Images/image1.jpg"
    "D:/MyProjects/GUIs/QT_QML_Course_KDAB/QT_QML_Course_KDAB/Images/image2.jpg"
    "D:/MyProjects/GUIs/QT_QML_Course_KDAB/QT_QML_Course_KDAB/QML_1/Images/image2.jpg"
    "D:/MyProjects/GUIs/QT_QML_Course_KDAB/QT_QML_Course_KDAB/Images/image3.jpg"
    "D:/MyProjects/GUIs/QT_QML_Course_KDAB/QT_QML_Course_KDAB/QML_1/Images/image3.jpg"
    "D:/MyProjects/GUIs/QT_QML_Course_KDAB/QT_QML_Course_KDAB/Images/image4.jpg"
    "D:/MyProjects/GUIs/QT_QML_Course_KDAB/QT_QML_Course_KDAB/QML_1/Images/image4.jpg"
    "D:/MyProjects/GUIs/QT_QML_Course_KDAB/QT_QML_Course_KDAB/Images/image5.jpg"
    "D:/MyProjects/GUIs/QT_QML_Course_KDAB/QT_QML_Course_KDAB/QML_1/Images/image5.jpg"
    "D:/MyProjects/GUIs/QT_QML_Course_KDAB/QT_QML_Course_KDAB/Images/image6.jpg"
    "D:/MyProjects/GUIs/QT_QML_Course_KDAB/QT_QML_Course_KDAB/QML_1/Images/image6.jpg"
    "D:/MyProjects/GUIs/QT_QML_Course_KDAB/QT_QML_Course_KDAB/Images/image7.jpg"
    "D:/MyProjects/GUIs/QT_QML_Course_KDAB/QT_QML_Course_KDAB/QML_1/Images/image7.jpg"
    "D:/MyProjects/GUIs/QT_QML_Course_KDAB/QT_QML_Course_KDAB/Images/image8.jpg"
    "D:/MyProjects/GUIs/QT_QML_Course_KDAB/QT_QML_Course_KDAB/QML_1/Images/image8.jpg"
    "D:/MyProjects/GUIs/QT_QML_Course_KDAB/QT_QML_Course_KDAB/Images/image9.jpg"
    "D:/MyProjects/GUIs/QT_QML_Course_KDAB/QT_QML_Course_KDAB/QML_1/Images/image9.jpg"

)
set(timestamp_file "D:/MyProjects/GUIs/QT_QML_Course_KDAB/QT_QML_Course_KDAB/.qt/appQML_1_res.txt")
